# Generated by Django 4.2.1 on 2023-06-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='sessionLength',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='loginTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='logoutTime',
            field=models.TimeField(),
        ),
    ]
