# Generated by Django 4.2.2 on 2023-06-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('aiportId', models.AutoField(primary_key=True, serialize=False)),
                ('airportName', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightId', models.AutoField(primary_key=True, serialize=False)),
                ('flightNumber', models.CharField(max_length=40)),
                ('seatingCapacity', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('arrivalTime', models.DateTimeField()),
                ('depatureTime', models.DateTimeField()),
                ('availableSeats', models.IntegerField()),
                ('basePrice', models.IntegerField()),
                ('destinationAirport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='loginapp.flight')),
                ('flightIdref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.flight')),
                ('sourceAirport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='loginapp.flight')),
            ],
        ),
    ]
